site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  logo: assets/lostesso.png
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy


plugins:
  - search
  - tags:
      tags_file: tags.md 
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - Home: index.md
 - Formazione:
    - Java: coding/my-first-java-file.md
    - Zoro: coding/zoro.md
 - About: about.md
 - Tags: tags.md
 - Blog:
    - blog/index.md

extra:
  consent:
    title: Hey! Dove credi di andare?
    description: >- 
      Sei un fallito che ha perso moglie, lavoro e amici? non preoccuparti, accettando qui sotto accetterai di
      vendere la tua anima al diavolo per la cifra di Euro 20, che ti permetterà di fare la tua ultima scommessa
      al casinò e sperare di riprenderti la tua vita. In caso contrario la SamFollSF.inc non si assume alcuna responsabilità.